appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RrqxNPXAovdeXz9Kj2H/2q8YWu6kUyQFke1/pblNl5GnsgpRKjzuDJ4ibcA7HP3wuVoQcVetHc0s43a3UTmMZJ8VNQBz554sl1ZZ7bkBRQzGhXg2PurJTBeQ2+EL7sQKdljyZ3DffHuXt6+eRB73iizRCqVgInDuNRp+xUfk6FYkj89FHhp0IWHRjPG8N1LP5pf5uzRRur1G3ADe3/5/AHhEmtFj8Z8ENM3XnfvxGKdkVLNgUooeK1ieMoifxvr+ewI1Jchz5ORZI/iq/QKyUw7cK6UfrzbqRIfwqp0aQ+BUuF02oI9s/1vLLPifM+dNjg44Yq55A6Z6HrLJjExdON/MYVJW0ZZfK3XPZkrYoCuelC7w/3BKauO26lpYTHu8VLgOyZjGQTv03zm3XJ2B0yVj48dMbDe1TN835C2zWQuHbT0Ev4+z6/JI7vajSf6BE+4xkVxdxJ8kGTaoKio1rx8wy8iYpM4dVttNm30VdDvHTCRjcTFgJIQPBIp7oJ43jTGLOScfhtMOcHyMnOJvC+jJmmECD+5TFeGYU0EAqJtEs8RwjQeFgl71/3ddWqaEmOYWOscqBZGLihFChVIA3f1q1lwAbSDP61C7CNqcJjK9MA0yADM22fhPVqzacg+580ayI6DHl2h7X1H/ycm61acFEQJ55qKm9pcNCfXVONs=}
